GET http://localhost:8080/api/id/2/gameStats
###
DELETE http://localhost:8080/api/2/gameStats
###
GET http://localhost:8080/api/id/2/gameStats/1

###
POST http://localhost:8080/api/id/2/gameStats
Content-Type: application/json

{
    "incomeVal": 0,
    "moraleVal":0,
    "emissionVal":0
}

###

PUT http://localhost:8080/api/id/2/gameStats/35
Content-Type: application/json
{
    "incomeVal": 10,
    "moraleVal":0,
    "emissionVal":0
}