### normal sign up
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "username": "johnTheUser2",
    "email": "johnNotTheAdmindTest2@gmail.com",
    "password": "password6*d123",
    "role": "USER"
}
###

### login
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
    "username": "johnTheUser2",
    "password": "password6*d123"
}
###

### get game info about this user
GET http://localhost:8080/api/gameInfo
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb2huVGhlVXNlcjIiLCJpYXQiOjE2Njc1NDQ4MjUsImV4cCI6MTY2NzU0ODQyNX0.uZ6PohfZpU8YU8qu0gEpE7GI4U1FvIFnq7LCL0cYpMg-8vL26zU7NsHvjnH05SvFNHkv9Yn-h4gIFBQmjMpWZw
###

### get game info about this user version 2
GET http://localhost:8080/api/gameInfo2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb2huVGhlVXNlcjIiLCJpYXQiOjE2Njc1NDQ4MjUsImV4cCI6MTY2NzU0ODQyNX0.uZ6PohfZpU8YU8qu0gEpE7GI4U1FvIFnq7LCL0cYpMg-8vL26zU7NsHvjnH05SvFNHkv9Yn-h4gIFBQmjMpWZw
###

### submit mcq answer #index from 0,1,2,3
GET http://localhost:8080/api/submitAnswer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb2huVGhlVXNlcjIiLCJpYXQiOjE2Njc1NDM4ODcsImV4cCI6MTY2NzU0NzQ4N30.ySFmjNCQ0CyLGFShjNmCa4PVoej7Go8vxJCSgCOaDEqkNWrwJeemP7qtcMx_I7qHLDeAjMT_md5mPnyPMfMm1w

{
    "answer": "2"
}

### submit open ended answer
GET http://localhost:8080/api/submitAnswer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb2huVGhlVXNlcjIiLCJpYXQiOjE2Njc1NDQ4MjUsImV4cCI6MTY2NzU0ODQyNX0.uZ6PohfZpU8YU8qu0gEpE7GI4U1FvIFnq7LCL0cYpMg-8vL26zU7NsHvjnH05SvFNHkv9Yn-h4gIFBQmjMpWZw

{
    "answer": "Electricity,Carbon,Water"
}